Update sector identifier guidance and registration process
govuk-one-login/authentication-tech-docs pull request #176
Opened 2024-02-09 16:35 UTC by sabrinaharris

## Why
We receive a lot of queries about the sector identifier which the tech docs do not explain in detail.

The sector identifier guidance needs more information so users can understand:
- what it is
- how and when to use it
- what format it should be in

## What

This PR:
- adds a separate page to explain the sector identifier and how to set it
- updates guidance around registering your service to include the sector identifier
- moves the generate key pair section to a more logical step in the process
- adds subheadings to 2 sections in the 'Contact the GOV.UK One Login team to register your service' section to make the user goal clearer

## Technical writer support

This has been through pre-i and 2i, @ImogenCraigmile to do final check. 

## How to review

Check the changes:
- are correct
- make sense
- follow existing style and relevant style guides
- do not contain jargon or terms our users are unlikely to know

@philf999 @pauldougan to check the fictional department example!

2024-02-12 09:56 UTC, philf999 requested changes
Looks good apart from the suggested change to the examples

2024-02-12 09:56 UTC, philf999 commented on source/before-integrating/choose-your-sector-identifier.html.md.erb
> +| Share users across some services    | Set the sector identifier in the services that share users to the same value. <br><br>Give the services that should not share users a different sector identifi
```suggestion
| Share users across some services    | Set the sector identifier in the services that share users to the same value. <br><br>Give the services that should not share users a different sector identifier. | Set `https://mythical-creatures.gov.uk` as the `sector_identifier_uri` for 'register your hydra' and 'report a unicorn' to share users. <br><br> Set `https://tax-your-dragon.mythical-creatures.gov.uk` as the `sector_identifier_uri` for 'tax your dragon' to have a separate user base.|
```

2024-02-13 14:16 UTC, pauldougan approved these changes
Looks good to me lets ship it 🚢

2024-02-13 14:38 UTC, ImogenCraigmile commented
I'll give this a once over now!

2024-02-13 14:52 UTC, ImogenCraigmile approved these changes
Ran it up locally and all looks good to me. The last reviewed date is the 9th of Feb, not sure if that has to be today the 13th or if it's inconsequential but just thought I'd mention!

2024-02-13 15:15 UTC, philf999 approved these changes

2024-02-14 13:47 UTC, huwd approved these changes

2024-02-14 13:47 UTC, merged